Param(
    [string]$ttl,
    [string]$text
)

Add-Type -AssemblyName System.Windows.Forms
[System.Windows.Forms.Application]::EnableVisualStyles()

$GUI                             = New-Object system.Windows.Forms.Form
$GUI.ClientSize                  = New-Object System.Drawing.Point(379,99)
$GUI.text                        = $ttl
$GUI.TopMost                     = $false
$GUI.Icon                        = "C:\Program Files\RaspiMote\logo\RaspiMote_logo.ico"

$Title                           = New-Object system.Windows.Forms.Label
$Title.text                      = $text
$Title.AutoSize                  = $true
$Title.width                     = 25
$Title.height                    = 10
$Title.location                  = New-Object System.Drawing.Point(19,17)
$Title.Font                      = New-Object System.Drawing.Font('Open Sans',10)

$TextBox1                        = New-Object system.Windows.Forms.TextBox
$TextBox1.multiline              = $false
$TextBox1.width                  = 180
$TextBox1.height                 = 20
$TextBox1.location               = New-Object System.Drawing.Point(80,50)
$TextBox1.Font                   = New-Object System.Drawing.Font('Open Sans',10)

$Button1                         = New-Object system.Windows.Forms.Button
$Button1.text                    = "Validate"
$Button1.width                   = 80
$Button1.height                  = 30
$Button1.location                = New-Object System.Drawing.Point(280,59)
$Button1.Font                    = New-Object System.Drawing.Font('Open Sans',10)


$GUI.controls.AddRange(@($Title,$TextBox1,$Button1))

$Button1.Add_Click(
    {
       Write-Output $TextBox1.text > $env:USERPROFILE\AppData\Roaming\RaspiMote\tmp\dialogTextOutput.txt
       $GUI.close()
    }
)

$GUI.ShowDialog()
# SIG # Begin signature block
# MIISsAYJKoZIhvcNAQcCoIISoTCCEp0CAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUM4mZqDMYhu3Q3GUNBMufUqAy
# GIOggg4zMIID+DCCA52gAwIBAgIBBDAKBggqhkjOPQQDAjCBxzELMAkGA1UEBhMC
# RlIxGTAXBgNVBAgMEMODwo5sZS1kZS1GcmFuY2UxOTA3BgNVBAcMMENoZW5uZXZp
# w4PCqHJlcy1zdXItTWFybmUgOyBMZSBQZXJyZXV4LXN1ci1NYXJuZTESMBAGA1UE
# CgwJUmFzcGlNb3RlMSowKAYDVQQDDCFSYXNwaU1vdGUgY2VydGlmaWNhdGlvbiBh
# dXRob3JpdHkxIjAgBgkqhkiG9w0BCQEWE3Jhc3BpbW90ZUBnbWFpbC5jb20wHhcN
# MjEwMjI0MDk0MDMxWhcNMzEwMjIyMDk0MDMxWjCBwzELMAkGA1UEBhMCRlIxGTAX
# BgNVBAgMEMODwo5sZS1kZS1GcmFuY2UxOTA3BgNVBAcMMENoZW5uZXZpw4PCqHJl
# cy1zdXItTWFybmUgOyBMZSBQZXJyZXV4LXN1ci1NYXJuZTESMBAGA1UECgwJUmFz
# cGlNb3RlMRIwEAYDVQQLDAlSYXNwaU1vdGUxEjAQBgNVBAMMCVJhc3BpTW90ZTEi
# MCAGCSqGSIb3DQEJARYTcmFzcGltb3RlQGdtYWlsLmNvbTBZMBMGByqGSM49AgEG
# CCqGSM49AwEHA0IABEACEI67iDSGmQ363jMgAbfO6fHAcAx2Gi7XkvISWNkOME0s
# aBSMNNiGmZ7DU2OQSITACSZlnqjHX+B8N3D3Lh+jggF6MIIBdjAdBgNVHQ4EFgQU
# /bAOYCbuspeSSIEKIOu6+XQePK0wgfwGA1UdIwSB9DCB8YAUPp1bepgAHzFe4jNl
# 5U4DEfFeVZyhgc2kgcowgccxCzAJBgNVBAYTAkZSMRkwFwYDVQQIDBDDg8KObGUt
# ZGUtRnJhbmNlMTkwNwYDVQQHDDBDaGVubmV2acODwqhyZXMtc3VyLU1hcm5lIDsg
# TGUgUGVycmV1eC1zdXItTWFybmUxEjAQBgNVBAoMCVJhc3BpTW90ZTEqMCgGA1UE
# AwwhUmFzcGlNb3RlIGNlcnRpZmljYXRpb24gYXV0aG9yaXR5MSIwIAYJKoZIhvcN
# AQkBFhNyYXNwaW1vdGVAZ21haWwuY29tggkA1prfibjB16owCQYDVR0TBAIwADAL
# BgNVHQ8EBAMCA6gwKwYDVR0lBCQwIgYIKwYBBQUHAwMGCisGAQQBgjcCARUGCisG
# AQQBgjcCARYwEQYJYIZIAYb4QgEBBAQDAgSwMAoGCCqGSM49BAMCA0kAMEYCIQDR
# /sSiX+jNoiEuw3/UhgRXTe9g3S4uuyzxZvT1MWERLAIhAJJuLO0TKz956d867jMV
# TWsY3Pz9eEhpxuG8Y2entT4JMIIE/jCCA+agAwIBAgIQDUJK4L46iP9gQCHOFADw
# 3TANBgkqhkiG9w0BAQsFADByMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNl
# cnQgSW5jMRkwFwYDVQQLExB3d3cuZGlnaWNlcnQuY29tMTEwLwYDVQQDEyhEaWdp
# Q2VydCBTSEEyIEFzc3VyZWQgSUQgVGltZXN0YW1waW5nIENBMB4XDTIxMDEwMTAw
# MDAwMFoXDTMxMDEwNjAwMDAwMFowSDELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDkRp
# Z2lDZXJ0LCBJbmMuMSAwHgYDVQQDExdEaWdpQ2VydCBUaW1lc3RhbXAgMjAyMTCC
# ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMLmYYRnxYr1DQikRcpja1HX
# OhFCvQp1dU2UtAxQtSYQ/h3Ib5FrDJbnGlxI70Tlv5thzRWRYlq4/2cLnGP9NmqB
# +in43Stwhd4CGPN4bbx9+cdtCT2+anaH6Yq9+IRdHnbJ5MZ2djpT0dHTWjaPxqPh
# Lxs6t2HWc+xObTOKfF1FLUuxUOZBOjdWhtyTI433UCXoZObd048vV7WHIOsOjizV
# I9r0TXhG4wODMSlKXAwxikqMiMX3MFr5FK8VX2xDSQn9JiNT9o1j6BqrW7EdMMKb
# aYK02/xWVLwfoYervnpbCiAvSwnJlaeNsvrWY4tOpXIc7p96AXP4Gdb+DUmEvQEC
# AwEAAaOCAbgwggG0MA4GA1UdDwEB/wQEAwIHgDAMBgNVHRMBAf8EAjAAMBYGA1Ud
# JQEB/wQMMAoGCCsGAQUFBwMIMEEGA1UdIAQ6MDgwNgYJYIZIAYb9bAcBMCkwJwYI
# KwYBBQUHAgEWG2h0dHA6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzAfBgNVHSMEGDAW
# gBT0tuEgHf4prtLkYaWyoiWyyBc1bjAdBgNVHQ4EFgQUNkSGjqS6sGa+vCgtHUQ2
# 3eNqerwwcQYDVR0fBGowaDAyoDCgLoYsaHR0cDovL2NybDMuZGlnaWNlcnQuY29t
# L3NoYTItYXNzdXJlZC10cy5jcmwwMqAwoC6GLGh0dHA6Ly9jcmw0LmRpZ2ljZXJ0
# LmNvbS9zaGEyLWFzc3VyZWQtdHMuY3JsMIGFBggrBgEFBQcBAQR5MHcwJAYIKwYB
# BQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBPBggrBgEFBQcwAoZDaHR0
# cDovL2NhY2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0U0hBMkFzc3VyZWRJRFRp
# bWVzdGFtcGluZ0NBLmNydDANBgkqhkiG9w0BAQsFAAOCAQEASBzctemaI7znGucg
# Do5nRv1CclF0CiNHo6uS0iXEcFm+FKDlJ4GlTRQVGQd58NEEw4bZO73+RAJmTe1p
# pA/2uHDPYuj1UUp4eTZ6J7fz51Kfk6ftQ55757TdQSKJ+4eiRgNO/PT+t2R3Y18j
# UmmDgvoaU+2QzI2hF3MN9PNlOXBL85zWenvaDLw9MtAby/Vh/HUIAHa8gQ74wOFc
# z8QRcucbZEnYIpp1FUL1LTI4gdr0YKK6tFL7XOBhJCVPst/JKahzQ1HavWPWH1ub
# 9y4bTxMd90oNcX6Xt/Q/hOvB46NJofrOp79Wz7pZdmGJX36ntI5nePk2mOHLKNpb
# h6aKLzCCBTEwggQZoAMCAQICEAqhJdbWMht+QeQF2jaXwhUwDQYJKoZIhvcNAQEL
# BQAwZTELMAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZMBcGA1UE
# CxMQd3d3LmRpZ2ljZXJ0LmNvbTEkMCIGA1UEAxMbRGlnaUNlcnQgQXNzdXJlZCBJ
# RCBSb290IENBMB4XDTE2MDEwNzEyMDAwMFoXDTMxMDEwNzEyMDAwMFowcjELMAkG
# A1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZMBcGA1UECxMQd3d3LmRp
# Z2ljZXJ0LmNvbTExMC8GA1UEAxMoRGlnaUNlcnQgU0hBMiBBc3N1cmVkIElEIFRp
# bWVzdGFtcGluZyBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAL3Q
# Mu5LzY9/3am6gpnFOVQoV7YjSsQOB0UzURB90Pl9TWh+57ag9I2ziOSXv2MhkJi/
# E7xX08PhfgjWahQAOPcuHjvuzKb2Mln+X2U/4Jvr40ZHBhpVfgsnfsCi9aDg3iI/
# Dv9+lfvzo7oiPhisEeTwmQNtO4V8CdPuXciaC1TjqAlxa+DPIhAPdc9xck4Krd9A
# Oly3UeGheRTGTSQjMF287DxgaqwvB8z98OpH2YhQXv1mblZhJymJhFHmgudGUP2U
# Kiyn5HU+upgPhH+fMRTWrdXyZMt7HgXQhBlyF/EXBu89zdZN7wZC/aJTKk+FHcQd
# PK/P2qwQ9d2srOlW/5MCAwEAAaOCAc4wggHKMB0GA1UdDgQWBBT0tuEgHf4prtLk
# YaWyoiWyyBc1bjAfBgNVHSMEGDAWgBRF66Kv9JLLgjEtUYunpyGd823IDzASBgNV
# HRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBhjATBgNVHSUEDDAKBggrBgEF
# BQcDCDB5BggrBgEFBQcBAQRtMGswJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRp
# Z2ljZXJ0LmNvbTBDBggrBgEFBQcwAoY3aHR0cDovL2NhY2VydHMuZGlnaWNlcnQu
# Y29tL0RpZ2lDZXJ0QXNzdXJlZElEUm9vdENBLmNydDCBgQYDVR0fBHoweDA6oDig
# NoY0aHR0cDovL2NybDQuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0QXNzdXJlZElEUm9v
# dENBLmNybDA6oDigNoY0aHR0cDovL2NybDMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0
# QXNzdXJlZElEUm9vdENBLmNybDBQBgNVHSAESTBHMDgGCmCGSAGG/WwAAgQwKjAo
# BggrBgEFBQcCARYcaHR0cHM6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzALBglghkgB
# hv1sBwEwDQYJKoZIhvcNAQELBQADggEBAHGVEulRh1Zpze/d2nyqY3qzeM8GN0CE
# 70uEv8rPAwL9xafDDiBCLK938ysfDCFaKrcFNB1qrpn4J6JmvwmqYN92pDqTD/iy
# 0dh8GWLoXoIlHsS6HHssIeLWWywUNUMEaLLbdQLgcseY1jxk5R9IEBhfiThhTWJG
# JIdjjJFSLK8pieV4H9YLFKWA1xJHcLN11ZOFk362kmf7U2GJqPVrlsD0WGkNfMgB
# sbkodbeZY4UijGHKeZR+WfyMD+NvtQEmtmyl7odRIeRYYJu6DC0rbaLEfrvEJStH
# Agh8Sa4TtuF8QkIoxhhWz0E0tmZdtnR79VYzIi8iNrJLokqV2PWmjlIxggPnMIID
# 4wIBATCBzTCBxzELMAkGA1UEBhMCRlIxGTAXBgNVBAgMEMODwo5sZS1kZS1GcmFu
# Y2UxOTA3BgNVBAcMMENoZW5uZXZpw4PCqHJlcy1zdXItTWFybmUgOyBMZSBQZXJy
# ZXV4LXN1ci1NYXJuZTESMBAGA1UECgwJUmFzcGlNb3RlMSowKAYDVQQDDCFSYXNw
# aU1vdGUgY2VydGlmaWNhdGlvbiBhdXRob3JpdHkxIjAgBgkqhkiG9w0BCQEWE3Jh
# c3BpbW90ZUBnbWFpbC5jb20CAQQwCQYFKw4DAhoFAKB4MBgGCisGAQQBgjcCAQwx
# CjAIoAKAAKECgAAwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGC
# NwIBCzEOMAwGCisGAQQBgjcCARYwIwYJKoZIhvcNAQkEMRYEFF8BMheecxLRyHqD
# H4cwM8erU0RCMAsGByqGSM49AgEFAARIMEYCIQCLPCuNAuC+aVsrkMQ1P6XBMgUb
# QY1zoyy75QcPPPwS8wIhALxFxARnQ7+1fE/FbZuBuc4MSIEdeR/vzqHH2bffGpsR
# oYICMDCCAiwGCSqGSIb3DQEJBjGCAh0wggIZAgEBMIGGMHIxCzAJBgNVBAYTAlVT
# MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j
# b20xMTAvBgNVBAMTKERpZ2lDZXJ0IFNIQTIgQXNzdXJlZCBJRCBUaW1lc3RhbXBp
# bmcgQ0ECEA1CSuC+Ooj/YEAhzhQA8N0wDQYJYIZIAWUDBAIBBQCgaTAYBgkqhkiG
# 9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0yMTAzMDExOTI3Mzla
# MC8GCSqGSIb3DQEJBDEiBCDY/FntIxUBMiZdnQ/FZ27RzU89twnhkvpPbRcHP8bC
# uDANBgkqhkiG9w0BAQEFAASCAQBXKgcvB20eUpi/ayNgeYEt0RLncX3NYk2gPr65
# 7nyt+SwbbEujUgjR5kXQLbt4oxtSK6iK+uyblfrF0cOystSBquYqySY12IH9mgOF
# AijfZqG+rfcAlZjW6FmFc+oTPAgnvpzwjJ4Zsj12qFqmuoaJV1yTz0WXqmTDdUgu
# TrglTeHKap51eC5IXV210BNfbodgWxAabhnl1kp2G4/YBws4cScy1R5MsY3itUqi
# kfjvp0FsjaM8Crp77h6jSdgOmZjkqXr1h3sU5TjaEAJl8jvzq2btSHhi0J0ATCe7
# UTqTmuON7qTZ2x5jgXHawLumFUfVGM9JwrHfoN6VQJq7bAdF
# SIG # End signature block
